version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Tjm12345*
      MYSQL_DATABASE: keep_control
      MYSQL_USER: keep_control_user
      MYSQL_PASSWORD: keep12345*
    ports:
      - "3333:3306"
    volumes:
      - ./data:/var/lib/mysql